version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocketledger_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
    volumes:
      - ./server:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/pocketledger_development

  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  pgdata:
