# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || 'himasha-e' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '1234' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: <%= ENV['DATABASE_URL'] ? nil : 'pocketledger_development' %>
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_URL'] ? nil : 'pocketledger_test' %>
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] ? nil : 'server_production' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'server' %>
  password: <%= ENV["SERVER_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
